# Generated by Django 4.2.22 on 2025-06-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rareapi", "0006_alter_user_created_alter_user_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
