# Generated by Django 4.2.22 on 2025-06-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rareapi", "0007_alter_comment_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
